### ISSUE TITLE
NullpointerException when following tutorial

### ISSUE THREAD

**Issue by fuchs257** [esa/nanosat-mo-framework#15]
The parameter tutorial at [readthedocs](https://nanosat-mo-framework.readthedocs.io/en/latest/apps/parameters.html) leads to a NullpointerException because the duration parameter in ParameterDefinitionDetails must not be 'null'.
Tutorial should be updated with `new Duration(0)` as fifth parameter.

**Comment by dmarszk** [comment]
Thank you! Fixed.
