### ISSUE TITLE
NanosatSupervisor: Could not find or load main class

### ISSUE THREAD

**Issue by fuchs257** [esa/nanosat-mo-framework#16]
Hi,
i have found a issue since last commit (dc79844001247):
When trying to start 
`target/nmf-sdk-2.0.0-SNAPSHOT/home/nmf/nanosat-mo-supervisor-sim/nanosat-mo-supervisor-sim.sh`
the error ` Error: Could not find or load main class esa.mo.nmf.nanosatmosupervisor.NanosatMOSupervisorBasicImpl `
 occurs.
Why has `esa.mo.nmf.provider.NanoSatMOSupervisorSoftSimImpl` been removed ? An where do i find the `esa.mo.nmf.nanosatmosupervisor.NanosatMOSupervisorBasicImpl` ? Is the dependency missing for maven build ?

**Comment by dmarszk** [comment]
Thanks for the report. Slipped by my QA build. Fixed.
