### ISSUE TITLE
Read the Docs may not be deployed with latest, most up to date version of docs

### ISSUE THREAD

**Issue by wbnns** [esa/nanosat-mo-framework#44]
For example, in https://nanosat-mo-framework.readthedocs.io/en/latest/sdk.html there is a typo:

<img width="723" alt="Screen Shot 2020-11-08 at 08 46 51" src="https://user-images.githubusercontent.com/1130872/98459840-9a272600-2196-11eb-99d4-504ccd84500b.png">

Yet, in `docs/source/sdk.rst` this is resolved. I suspect there are other typos and content updates that may not be reflected in the documentation on Read the Docs.

**Comment by dmarszk** [comment]
There's a build performance issue we seem to be hit by, causing the builds to timeout consistently.
See https://readthedocs.org/projects/nanosat-mo-framework/builds/

I think if we could cache the processed Javadoc data between consecutive sphinx-build invocations, that would help greatly.
Is this something you wanna look into @wbnns ?

**Comment by dmarszk** [comment]
Fixed. At least for the time.

**Comment by wbnns** [comment]
@dmarszk 

Thanks for fixing this! Apologies that I didn't get a chance to take a look and reply sooner; have been very busy on contract work and haven't been able to rotate back.
