### ISSUE TITLE
Adding GitHub topics to repository to improve discoverability

### ISSUE THREAD

**Issue by wbnns** [esa/nanosat-mo-framework#54]
@CesarCoelho 

In case helpful, just wanted to suggest that you can add [topics](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics) to this repository which will potentially help improve discoverability of it here on GitHub.

![image](https://user-images.githubusercontent.com/1130872/102685603-3d317d80-41e2-11eb-8101-9c61f766fc10.png)

Ideas for topics:
+ esa
+ space
+ satellites
+ nanosatellites
+ frameworks
+ java

**Comment by CesarCoelho** [comment]
Done

**Comment by wbnns** [comment]
Looks good!
