### ISSUE TITLE
build_batch_script.xml bugs

### ISSUE THREAD

**Issue by KOlfe** [esa/nanosat-mo-framework#6]
Hi,
It seems that there are two minor bugs in the "build_batch_script.xml" file:
In line 6: after REM a space is necessary.
In line 17: \etc: should be \etc;

This is the new file:
[build_batch_script.zip](https://github.com/esa/nanosat-mo-framework/files/3329712/build_batch_script.zip)

**Comment by yannickl96** [comment]
Hello KOIfe,
this should be fixed on the dev branch. With https://github.com/esa/nanosat-mo-framework/commit/e99134f1af3156a5126dcaac6dacfdde404a49ab . 
Please try checking out the dev branch and see if it works.

**Comment by KOlfe** [comment]
It works.

Thank you Yannick.

**Comment by yannickl96** [comment]
No problem :)
